gym_sys/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='home'),
    path('pagedetail/<int:id>/', views.page_detail,name='pagedetail'),
    path('faq/', views.faq_list,name='faq'),
    path('enquiry/', views.enquiry,name='enquiry'),
    path('gellary/', views.gellary,name='gellary'),
    path('gellarydetail/<int:id>/', views.gellary_detail,name='gallery_detail'),
    path('pricing/', views.pricing,name='pricing'),

    path('checkout/<int:plan_id>/', views.checkout,name='checkout'),

    #accounts::::::trainer (login,profile, dashboard,
    path('accounts/signup/', views.signup,name='signup'),
    path('trainerlogin/', views.trainerlogin,name='trainerlogin'),
    path('trainer_changepassword/', views.trainer_password_change,name='trainer_changepassword'),
    path('trainerlogout/', views.trainerlogout,name='trainerlogout'),
    path('trainer_dashboard/', views.trainer_dashboard, name='trainer_dashboard'),
    path('trainer_profile/', views.trainer_profile, name='trainer_profile'),
    path('trainer_subcriber/', views.trainer_subcriber, name='trainer_subcriber'),
    path('trainer_payments/', views.trainer_payments, name='trainer_payments'),
    path('trainer_notifs/', views.trainer_notifs, name='trainer_notifs'),
    path('trainer_message/', views.trainer_message, name='trainer_message'),

    #notifications
    path('notification/', views.notification,name='notification'),
    path('get_notifs/', views.get_notifs,name='get_notifs'),
    path('mark_as_read/<int:notification_id>/', views.mark_as_read, name='mark_as_read'),

    #dashboard work
    path('user_dashboard/', views.user_dashboard,name='user_dashboard'),
    path('update_profile/', views.update_Profile,name='update_profile'),
]

gym_sys/gym_sys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

gym_sys/app/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Banners(models.Model):
    img=models.ImageField(upload_to='banners/')
    alt_text=models.CharField(max_length=150)
    class Meta:
        verbose_name_plural='Banners'
    def __str__(self) -> str:
        return self.alt_text
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' %(self.img.url))
class Service(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to='services/')

    def __str__(self) -> str:
        return self.title
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' %(self.img.url))
class Pages(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()

    def __str__(self) -> str:
        return self.title
class Faq(models.Model):
    ques=models.TextField()
    ans=models.TextField()
    
    def __str__(self) -> str:
        return self.ques
    # enter you data
class Enquiry(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.CharField(max_length=150)
    detail=models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.full_name

class Gallery(models.Model):
    title=models.CharField(max_length=150)
    img=models.ImageField(upload_to='gellary/',null=True)
    detail=models.TextField()
    def __str__(self) -> str:
        return self.title
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' %(self.img.url))
# All gellary Image show by this model
class GalleryImage(models.Model):
    gellary=models.ForeignKey(Gallery,on_delete=models.CASCADE, null=True)
    alt_text=models.CharField(max_length=150)
    img=models.ImageField(upload_to='gellary_images/',null=True)
    def __str__(self) -> str:
        return self.alt_text
    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' %(self.img.url))

#subcription plan::::::::
class SubcripPlan(models.Model):
    title=models.CharField(max_length=150)    
    price=models.IntegerField()    
    max_member=models.IntegerField(null=True)    
    highlight_status=models.BooleanField(default=False,null=True)
    validate_time=models.IntegerField(null=True)    
    def __str__(self) -> str:
        return self.title

#subcription Feature asigned
class SubcripPlanFeature(models.Model):
    # subcripplan=models.ForeignKey(SubcripPlan,on_delete=models.CASCADE)   
    subcripplan=models.ManyToManyField(SubcripPlan)   
    title=models.CharField(max_length=150)     
    def __str__(self) -> str:
        return self.title 
# here creating amount 
class PlanDiscount(models.Model):
    subcripplan=models.ForeignKey(SubcripPlan,on_delete=models.CASCADE,null=True)
    total_month=models.IntegerField()
    total_discount=models.IntegerField()
    def __str__(self) -> str:
        return str(self.total_month)
# subcribe model
class Subscriber(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    mobile=models.CharField(max_length=20)
    address=models.TextField()
    img=models.ImageField(upload_to='subscriber/',null=True)
    def __str__(self) -> str:
        return str(self.user)
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' %(self.img.url)) 
        else:
            return 'No Image'
# create subcription here
class Subscription(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    plan=models.ForeignKey(SubcripPlan,on_delete=models.CASCADE,null=True)
    price=models.CharField(max_length=50)
    regis_date=models.DateTimeField(auto_now_add=True,null=True)

@receiver(post_save,sender=User)
def create_subcriber(sender,instance,created,**kwargs):
    if created:
        Subscriber.objects.create(user=instance)
class Trainer(models.Model):
    full_name=models.CharField(max_length=150)
    username=models.CharField(max_length=150,null=True)
    password=models.CharField(max_length=50,null=True)
    mobile=models.CharField(max_length=150)
    salary=models.IntegerField(default=0)
    address=models.TextField()
    is_active=models.BooleanField(default=False)
    detail=models.TextField()
    img=models.ImageField(upload_to='trainer/',null=True)
    def __str__(self) -> str:
        return str(self.full_name)
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' %(self.img.url)) 
# CSV file Attached here
class TrainerCSV(models.Model):
    trainercsv=models.FileField(upload_to='trainercsv/',null=True)
class Notify(models.Model):
    notify_detail=models.TextField()
    readby_user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    readby_trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE,blank=True,null=True)
    is_read = models.BooleanField(default=False)
    def __str__(self) -> str:
        return str(self.notify_detail) 
# sibscriber --> Trainer 
class AssignSubscriber(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE,blank=True)

    def __str__(self) -> str:
        return str(self.user)
# achivements of Trainer
class TrainerAchivements(models.Model):
    trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE,null=True)
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to='achivements/',null=True)
    class Meta:
        verbose_name_plural='TrainerAchivements'
    def __str__(self) -> str:
        return str(self.title)
    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80" />' %(self.img.url)) 
        else:
            return 'No image'

#Trainer Salary include
class Trainersalary(models.Model):
    trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE)
    amount=models.IntegerField()
    amount_date=models.DateField()
    remarks=models.TextField(blank=True)
    def __str__(self) -> str:
        return str(self.trainer.full_name)
    class Meta:
        verbose_name_plural='Trainer Salary'
# Trainer Notifications.....
class TrainerNotifications(models.Model):
    notif_msg = models.TextField()
    def __str__(self) -> str:
        return self.notif_msg
    class Meta:
        verbose_name_plural='Trainer Notifications'
# create notifTrainer status for create relationship...
class NotifTrainerStatus(models.Model):
    notif=models.ForeignKey(TrainerNotifications,on_delete=models.CASCADE)
    trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    class Meta:
        verbose_name_plural='Trainer Notification Status'
# subscriber message model 
class Trainermsg(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    trainer=models.ForeignKey(Trainer,on_delete=models.CASCADE,null=True)
    message = models.TextField()

    class Meta:
        verbose_name_plural='Message for Trainer'

gym_sys/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'assets/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
    <!-- jquery -->
    <script src="{% static 'assets/jquery-3.6.0.min.js' %}"></script>
    <title>Home - GYM</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #007bff;">
	  <div class="container">
	    <a class="navbar-brand" href="{% url 'home' %}">Your GYM</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gellary' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link btn btn-sm " href="{% url 'enquiry' %}">Enquiry</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            {{request.user}}
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
			  {% if not request.user.is_authenticated %}
			    
					{% if request.session.trainerlogin %}
						<li><a class="dropdown-item" href="{% url 'trainer_dashboard' %}" class="list-group-item {% if request.path == '/trainer_dashboard/' %} active {% endif %}">Dashboard</a></li>
						<li><a class="dropdown-item" href="{% url 'trainerlogout' %}">Logout</a></li>
					{% else %}
						<li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a></li>
						<li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
	            		<li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
					{% endif %}
				{% else %}
	            <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a></li>
	            <li><a class="dropdown-item" href="#">Profile</a></li>
	            <li><a class="dropdown-item" href="#">Settings</a></li>
	            <li>
					<form method="post" action="{% url 'logout' %}">
						{% csrf_token %}
						<button type="submit" class="dropdown-item">Logout</button>
					</form>
				</li>
				{% endif %}
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->
{% if mesages %}
					{% for message in messages %}
						<p class="text-{{message.tag}}">{{message}}</p>
					{% endfor %}
				{% endif %}
{% block content %}

{% endblock content %}

        <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	    <p>Copyright © 2024 . All rights reserved. GYM, Inc. · 
            <a href="{% url 'pagedetail' 2 %}">Privacy</a> · 
            <a href="{% url 'pagedetail' 3 %}">Terms</a> . 
            <a href="{% url 'faq' %}">FAQ</a>
        </p>
	  </footer>

    <!-- Bootstrap Bundle -->
    <script src="{% static 'assets/bootstrap.bundle.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'assets/popper.min.js' %}"></script>

  </body>
</html>

gym_sys/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
				<table class="table table-bordered">
					<thead class="table-warning">
						<tr>
							<th>Plan</th>
							<th>Plan Detail</th>
							<th>Payment For</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<table class="table-bordered table">
									<tr>
										<th>Name</th>
										<td>{{plan.title}}</td>
									</tr>
									<tr>
										<th>Price</th>
										<td>${{plan.price}}</td>
									</tr>
									<tr>
										<th>Max Member</th>
										<td>{{plan.max_member}}</td>
									</tr>
									<tr>
										<th>Already Registered</th>
										<td>15</td>
									</tr>
									<tr>
										<th>Balance Seats</th>
										<td>15</td>
									</tr>
								</table>
							</td>
							<td>
								<ul class="list-unstyled">
					            {% for feature in plan.subcripplanfeature_set.all %}
                                    <li>{{ feature.title }}</li>
                                {% endfor %}
					            </ul>
							</td>
							<td>
								<table class="table table-bordered">
                                 {% for discount in plan.plandiscount_set.all %}
									<tr>
										<td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity1" name="validity" class="select-validity" value="{{discount.total_month}}" /></td>
										<th><label for="validity{{discount.id}}">{{discount.total_month}} Month</label></th>
										<td>{{discount.total_discount}}%</td>
									</tr>
                                    {% endfor %}
									
								</table>
							</td>
						</tr>
					</tbody>
					<tfoot class="table-info">
						<tr>
							<td></td>
							<th>Total Amount</th>
							<td><b>$<span class="totalAmount">{{plan.price}}</span></b></td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td>
							<form action="" method='POST'>
								<input type="submit" value="Proceed to Payment" class="btn btn-primary" /></td>
							</form>
						</tr>
					</tfoot>
				</table>
		</section>
		<!-- End -->
    </main>
    <!-- End -->

<script type="text/javascript">
	$(document).ready(function(){
		$(".select-validity").on('click',function(){
			var _planPrice=$(this).attr('data-planprice');
			var _planDisc=$(this).attr('data-discount');
			var _planValid=$(this).val();
			var _totalPrice=_planPrice*_planValid;
			if(_planDisc>0){
				var _discountedPrice=_totalPrice*_planDisc/100;
				_discountedPrice=_totalPrice-_discountedPrice;
			}else{
				var _discountedPrice=_totalPrice;
			}
			$(".totalAmount").text(_discountedPrice);
		});
	});
</script>

{% endblock %}

gym_sys/templates/dashboard.html
{% extends 'base.html' %}

    <!-- Main Start -->
    {% block content %}
    <main>
		<!-- Services -->
		<section class="container my-4">
			<div class="row">
                <div class="col-3">
                    {% include 'left_sidebar.html' %}
                </div>
                <div class="col-9">
                    <h3 class="mb-4 border-bottom pd-1">Dashboard</h3>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card">
                                <h5 class="card-header">current package</h5>
                                <div class="card-body">
                                    <h6 class='card-text'>{{current_plan.plan}}</h6>
                                    <p >Price: {{current_plan.price}}</p>
                                    <p >Purchase Date:{{current_plan.regis_date.date}}</p>
                                    <p >Expired Date:{{endtime.date}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card" style="width: 15rem;">
                            
                                <h5 class="card-header">Assign Trainer </h5>
                                <img src="{{my_trainer.trainer.img.url}}" class="card-img-top" alt="{{my_trainer.trainer.full_name}}">
                                <div class="card-body">
                                    <h6 class='card-text'>{{my_trainer.trainer.full_name}}</h6>
                                </div>
                                <div class="card-footer">
                                <a href="#" title='Facebook' class='btn btn-primary btn-sm'><i class="bi bi-facebook"></i></a>
                                <a href="#" title='Twitter' class='btn btn-info btn-sm'><i class="bi bi-twitter"></i></a>
                                <a href="#" title='Whatsapp' class='btn btn-success btn-sm'><i class="bi bi-whatsapp"></i></a>
                                <a href="#" title='Whatsapp' class='btn btn-danger btn-sm'><i class="bi bi-youtube"></i></a>
                                <button data-bs-toggle="modal" data-bs-target="#achivementsModal"  title='achivements' class='btn btn-sm btn-success float-end'><i class="bi bi-trophy-fill"></i></button>
                                
<!-- Modal -->
<div class="modal fade" id="achivementsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{my_trainer.trainer.full_name}} Achivements</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
            <thead>
              <tr>
               <th>Title</th>
               <th>Image</th>
               <th>Details</th>
              </tr>
            </thead>

            <tbody>
            {% for achieve in my_trainer.trainer.trainerachivements_set.all %}
              <tr>
                <td>{{achieve.title}}</td>
                <td><img src="{{achieve.img.url}}" width='80' alt="Image"></td>
                <td>{{achieve.detail}}</td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>                                
                                
                                
                                
                                
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
	{% endblock content %}

gym_sys/templates/edit_profile.html
{% extends 'base.html' %}

    <!-- Main Start -->
    {% block content %}
    <main>
		<!-- Services -->
		<section class="container my-4">
			<div class="row">
                <div class="col-3">
                    {% include 'left_sidebar.html' %}
                </div>
                <div class="col-9">
                    <h3 class="mb-4 border-bottom pb-1">Update Profile</h3>
                    
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <form action="" method='POST'>
                        <table class='table table-bordered'>
                        {% csrf_token %}
                        {{ form.as_table }}
                            <tr>
                                <td class="colspan-2">
                                    <input type="submit" class='btn btn-primary'>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
	{% endblock content %}

gym_sys/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'imgs/enquiry.jpg' %}" class="img-fluid" /> 
				</div>

				<div class="col-md-6">
				{% if messages %}
					<ul class="messages">
						{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
						{% endfor %}
					</ul>
				{% endif %}
					<form action='{% url 'enquiry' %}' method='POST'>{% csrf_token %}
						<table class="table table-bordered">
							{{form.as_table}}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock content %}

gym_sys/templates/faq.html
{% extends 'base.html' %}

    <!-- Main Start -->
    {% block content %}
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
			<div class="accordion" id="accordionExample">
			{% for faq in faqs %}
			  <div class="accordion-item">
			    <h2 class="accordion-header" id="headingOne">
			      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
			       	{{faq.ques}}
			      </button>
			    </h2>
			    <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
			      <div class="accordion-body">
			        <strong>{{faq.ans}}</strong>
			      </div>
			    </div>
			  </div>
			 {% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
	{% endblock content %}

gym_sys/templates/gellary.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
			<div class="row">
				{% for gal in gellary %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                        <img src="{{gal.img.url}}" class="card-img-top" alt="{{gal.title}}">
                        <div class="card-body">
                            <h5 class="card-title">{{gal.title}}</h5>
                            <p class="card-text">{{gal.detail}}</p>
                            <a href="{% url 'gallery_detail' gal.id %}" class="btn btn-primary">View All</a>
                          
                        </div>
                        </div>
                    </div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

gym_sys/templates/gellary_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gellary.title|capfirst}} Images</h1>
			<div class="row">
				{% for gal in gellary_images %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                          <a data-lightbox="home-gallery" href="{{gal.img.url}}">  <img src="{{gal.img.url}}"class="card-img-top" alt="{{gal.alt_text}}"></a>
                        </div>
                    </div>
				{% endfor %}
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
    <!-- LightBox css -->
<link rel="stylesheet" type="text/css" href="{% static 'lightbox2-2.11.3/dist/css/lightbox.min.css' %}" />
<!-- LightBox Js -->
<script type="text/javascript" src="{% static 'lightbox2-2.11.3/dist/js/lightbox.min.js' %}"></script>

{% endblock %}

gym_sys/templates/page.html
{% extends 'base.html' %}
{% load static %}
    <!-- Main Start -->
    {% block content %}
    <main>

<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{pages.title}}</h1>
			<p>{{pages.detail}}</p>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock content %}
{% comment %} <script type="text/javascript" src="assets/lightbox2-2.11.3/dist/js/lightbox.min.js"></script>
<link rel="stylesheet" type="text/css" href="assets/lightbox2-2.11.3/dist/css/lightbox.min.css" />
 {% endcomment %}

gym_sys/templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% load check_package %} 
{% load mathfilters %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
<section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
            {% if plan.highlight_status %}
             <div class="card-header py-3 text-white bg-primary border-primary">
            {% else %}
                <div class="card-header py-3">
            {% endif %}
                <h4 class="my-0 fw-normal">{{plan.title}}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">${{plan.price}}<small class="text-muted fw-light">/{{plan.validate_time}}Days</small></h1>
                <p class='text-success'>Member Capecity: {{plan.max_member|sub:plan.total_member}}</p>
                <ul class="list-unstyled mt-3 mb-4">
                 {% for feature in plan.subcripplanfeature_set.all %}
                    <li>{{ feature.title }}</li>
                 {% endfor %}
                </ul>
                
                 {% check_user_package request.user.id plan.id as check_pckg %}


                {% if request.user.is_authenticated %}
                    {% if check_pckg %}
                        <a href="#" class="w-100 btn btn-lg btn-dark disabled">Purchased</a>
                     {% else %}
                        <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
                    {% endif %}

                    
                {% else %}
                    <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
                {% endif %}
               
                
                </div>
            </div>
        </div>
    {% endfor %}

    </div>

        <h2 class="display-6 text-center mb-4">Compare plans</h2>

        <div class="table-responsive">
        <table class="table text-center">
            <thead>
            <tr>
                <th style="width: 34%;"></th>
                 {% for plan in plans %}
                    <th style="width: 22%;">{{plan.title}}</th>
                 {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for feature in dfeatures %}
                <tr>
                    <th scope="row" class="text-start">{{feature.title}}</th>
                    {% for plan in plans %}
                        <td>
                        {% if plan in feature.subcripplan.all %}
                            <i class="bi bi-check-lg"></i>
                        {% else %}
                            <i class="bi bi-x-lg text-danger"></i>
                        {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
  </main>
</section>
{% endblock content %}